name: Docker Image CI

on:
  push:
    branches:
      - "feat/internet-sync"
    paths:
      - "**"

env:
  CLUSTER_NAME: goat-mainnet
  ECR_REPOSITORY: goat-network
  IMAGE_NAME: goat-relayer

jobs:
  build-and-deploy:
    name: Build and Deploy Module
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ 'goat-relayer' ]
    environment: mainnet

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: 'true'

      - name: Checkout code with full history
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get images version
        id: version
        run: |
          LAST_PUSH=$(git rev-list --count HEAD)
          TIMES=$(TZ='Asia/Shanghai' date +'%Y%m%d')
          VERSION=$TIMES-$LAST_PUSH
          TAG=v$VERSION
          echo "VERSION=$TAG" >> $GITHUB_ENV


      - name: Build and push image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          
          docker build --build-arg GITHUB_TOKEN=${{ secrets.TOKEN }} -t goatnetwork/goat-relayer:${{ env.VERSION }}-test -f ./Dockerfile .
          docker push goatnetwork/goat-relayer:${{ env.VERSION }}-test
          echo "image=goatnetwork/goat-relayer:${{ env.VERSION }}-test" >> $GITHUB_OUTPUT
          echo "image_tag=${{ env.VERSION }}-test" >>  $GITHUB_OUTPUT